### PR TITLE
Create site for Chimera 

### PR DESCRIPTION
**Pull request by sundapeng**
Fix https://github.com/intel-hadoop/chimera/issues/85 , enable site for Chimera
`mvn site` can generate the website at target/site
I also uploaded it to http://project.sundp.me/chimera, once the pr is committed, I will sync it to http://intel-hadoop.github.io/chimera/

### CODE REVIEW

**Comment by jerrychenhf** [comment]
HI @sundapeng , Thanks for investigating and contribute this. I have a few of questions:
1. Is this the same way as Apache Commons?
2. Our template/contents follows the same structure as Apache Commons modules?
      a. Navigation menu
      b. Content structure

**Comment by sundapeng** [comment]
Thank @jerrychenhf for your comments. Here are my replies
`1. Is this the same way as Apache Commons?`
Yes, the pr will enable `mvn site`, it will generate website like other components at Apache commons 
`2. Our template/contents follows the same structure as Apache Commons modules?`
`a. Navigation menu`
`b. Content structure`
Both are yes, the templates referred https://commons.apache.org/proper/commons-net/  and https://commons.apache.org/proper/commons-codec/ . the pages: mailing-list, Issue-tracking,download is generated by plugin, index.xml proposal.xml and site.xml(navigation) can be customed.

**Comment by jerrychenhf** [comment]
Thanks @sundapeng for the answers. And it's very good.
One thing is the name. We are assuming the name Chimera a lot of places in the document.
Although the Apache commons is discussing the name, it would be something like:
Apache Commons Crypto
Apache Commons FastCrypt
Apache Commons AES

Apache Commons Crypto has a high possibility of win. So we can use this name.

We would better not plan to merge the Commons site stuff to our master branch. Because this are specific to Apache Commons things. We can create a dedicated branch for this.  And we merge it to the branch.

**Comment by sundapeng** [comment]
I'm agreed with you, I will create branch `apache`, and change target branch of the pr to `apache`

**Pull request closed without merging**
