### PR TITLE
issue-83: Remove duplicated read(byte[] b, int off, int len) in CTRCryptoInputStream

### PR DESCRIPTION
**Pull request by colinmjj**
The pull request for https://github.com/intel-hadoop/chimera/issues/83.

### CODE REVIEW

**Comment by jerrychenhf** [comment]
Looks good to me. Make sure that others can review and to validate this change is correct.

**Comment by winningsix** [comment]
LGTM. Thanks for the patch.

**Comment by jerrychenhf** [comment]
LGTM

**Comment by jerrychenhf** [comment]
By the way the commit message should be meaningful. "Issue 81", "Issue 83" are meaningless at the context there is no reference for issues.

**Comment by colinmjj** [comment]
The commit message is updated, thanks for catch that.

**Comment by jerrychenhf** [comment]
Thanks @colinmjj for updating. Ready to go.

**Pull request merged**
