### PR TITLE
[SMALL-FIX] remove duplicated cases in TestData

### PR DESCRIPTION
**Pull request by dongche**
A small fix to remove the duplicated test cases in TestData.

### CODE REVIEW

**Comment by jerrychenhf** [comment]
Thanks @dongche.
Maybe @sundapeng can help a review.

**Comment by sundapeng** [comment]
@jerrychenhf @dongche Sure, I will look into it, thanks.

**Comment by sundapeng** [comment]
These tests are testing different plainTexts with same key and iv. They are not duplicated. But I think we can reduce some of them. Thank @dongche

**Comment by dongche** [comment]
Right, reasonable. Retrieve some cases to ensure every same key having 2 cases of different plainText. Thanks for your feedback, @sundapeng

**Comment by sundapeng** [comment]
Thank @dongche for your contribution! Merged to master.

**Pull request merged**
