### PR TITLE
Don't invoke sbt from the makefile.

### PR DESCRIPTION
**Pull request by vanzin**
This avoids rebuilding everything with sbt when running "mvn install".
Also avoid copying the generated library to the source directory.

### CODE REVIEW

**Comment by winningsix** [comment]
LGTM @dianfu any further comments?

**Comment by dianfu** [comment]
Currently sbt is used to do both packaging and publishing the jar to maven central repository. I'm ok to remove sbt from the makefile. But we should add the functionality to publish the jar the maven central repository using maven plugin.

**Comment by vanzin** [comment]
Why have sbt in the build here at all? It's such a small library, maven is more than enough. Just "mvn deploy" to upload to maven central should be enough, no?

**Comment by dianfu** [comment]
Agree that maven is enough to do that. But it's so easy as you said that "maven deploy" is enough.  For example, you need to generate a PGP signature for the jar. Anyway, I'm +1 to use maven to do that.

**Comment by dianfu** [comment]
+1 on this PR. I will create a separate PR to cover the necessary changes to publish the jar to maven central repository.

**Pull request merged**
